2019-09-18 10:29:11,983 [1] DEBUG Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient - GetRequestContent generated JSON: {"instance":{"instanceId":"CathyZhou-MAC:unknown:80","app":"UNKNOWN","appGroupName":null,"ipAddr":"193.100.100.114","sid":"na","port":{"@enabled":true,"$":5000},"securePort":{"@enabled":false,"$":443},"homePageUrl":"http://localhost:5000/","statusPageUrl":"http://localhost:5000/info","healthCheckUrl":"http://localhost:5000/health","secureHealthCheckUrl":null,"vipAddress":null,"secureVipAddress":null,"countryId":1,"dataCenterInfo":{"@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo","name":"MyOwn"},"hostName":"localhost","status":"UP","overriddenstatus":"UNKNOWN","leaseInfo":{"renewalIntervalInSecs":30,"durationInSecs":90,"registrationTimestamp":0,"lastRenewalTimestamp":0,"renewalTimestamp":0,"evictionTimestamp":0,"serviceUpTimestamp":0},"isCoordinatingDiscoveryServer":false,"metadata":{"@class":"java.util.Collections$EmptyMap"},"lastUpdatedTimestamp":1568773751823,"lastDirtyTimestamp":1568773751823,"actionType":"ADDED"}}
2019-09-18 10:29:16,147 [8] ERROR Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient - RegisterAsync Exception:
2019-09-18 10:29:16,154 [8] ERROR Steeltoe.Discovery.Eureka.DiscoveryClient - Register failed, Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8761
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   在 System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.<RegisterAsync>d__12.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Steeltoe.Discovery.Eureka.DiscoveryClient.<RegisterAsync>d__61.MoveNext()
2019-09-18 10:29:16,154 [8] DEBUG Steeltoe.Discovery.Eureka.DiscoveryClient - Register failed
2019-09-18 10:29:16,155 [1] INFO  Steeltoe.Discovery.Eureka.DiscoveryClient - Registartion fail. HeartBeat not start
2019-09-18 10:29:16,156 [1] INFO  FortuneTeller.Common.EurekaSupport - Discovery service started!
2019-09-18 10:29:16,159 [1] INFO  FortuneTellerService4.WebApiApplication - Fortunes populated!
2019-09-18 10:29:16,159 [1] INFO  FortuneTellerService4.WebApiApplication - Finished Application_Start
